default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: band_api_development
  username: postgres
  password: admin123
  
test:
  <<: *default
  database: band_api_test
  username: postgres
  password: admin123

production:
  <<: *default
  database: band_api_production
  username: band_api
  password: <%= ENV["BAND_API_DATABASE_PASSWORD"] %>
